name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.0.0'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: yarn run build

      - name: Push to published branch to deploy to "ewsgit.uk"
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: published
          FOLDER: ./dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
